# Project information
site_name: 'TJU'
site_description: '2022-2023_TJU_数字工程笔记'


# Repository
repo_name: '仓库'
repo_url: 'https://github.com/TongJiVex/2022-2023_TJU_Engineering_Notebook'

# Copyright
copyright: '2023 VEX TJU'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'static/imgs/TongJiVex.ico'

plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  utteranc:
    repo: ansible
    issueTerm: pathname
    theme: github-light
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/TongJiVex/2022-2023_TJU_Engineering_Notebook'


extra_javascript:
  - 'static/js/jquery-3.1.1.min.js'

nav:
  - "Engineering_Notebook": index.md

